<?php

namespace App\Model;

use Framework\Core\Model;

class Category extends Model
{
    protected $id;

    public string $name;

    public ?string $created_at;

    public function attributes(): array
    {
        return ['name', 'created_at'];
    }

    public function getId(): int
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getAllCategory(): array
    {
        return parent::findAll();
    }

    public function getOneCategory($id)
    {
        return parent::findOne($id);
    }

    public function save()
    {
        parent::save();
    }

    public function deleteCategory(int $id)
    {
        parent::delete($id);
    }

    protected static function getTableName(): string
    {
        return "Category";
    }
}
